puts "This is printed by Simon."
puts "This is printed by Simon."
puts "This is printed by Simon."
#puts "This is printed by Simon."
#puts "This is printed by Simon."
#puts "This is printed by Simon."
